### ISSUE TITLE
Lineageos 18.1 microg Permission Manager Does not work 

### ISSUE THREAD

**Issue by Exodusnick** [lineageos4microg/docker-lineage-cicd#176]
I build via docker.sh lineageos 18.1 for Samsung S7 flat and Samsung S7 edge with the sources of lineageos.

docker run \
    -e "BRANCH_NAME=lineage-18.1" \
    -e "DEVICE_LIST=herolte,hero2lte" \
    -e "SIGN_BUILDS=true" \
    -e "WITH_SU=false" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "UNIFIEDNLP_SUPPORT=true" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension" \
    -e "RELEASE_TYPE=microG-signed" \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/lineage:/srv/src" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/zips:/srv/zips" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/logs:/srv/logs" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/cache:/srv/ccache" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/keys:/srv/keys" \
    -v "/home/exodusnick/lineageos_microG/18.1_microG/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd

Sources from lineageos

https://github.com/LineageOS/android_device_samsung_hero2lte
https://github.com/LineageOS/android_device_samsung_herolte
https://github.com/LineageOS/android_kernel_samsung_universal8890
https://github.com/LineageOS/android_hardware_samsung
https://github.com/fcuzzocrea/proprietary_vendor_samsung https://github.com/LineageOS/android_device_samsung_slsi_sepolicy

Sources from lineageos4microg

https://github.com/lineageos4microg/android_prebuilts_prebuiltapks

Changes
https://pastebin.com/naZ4NfMW
And
git revert a413b6ee55636766dc61644bc1fc899117fb4aca
In vendor/lineage

The build is also finished and everything works except the Permission Manager.

This is with microg:
![1144](https://user-images.githubusercontent.com/24758741/115127535-90bca800-9fd7-11eb-8cd7-54cb39aa1e51.jpg)

And this without microg:
![IMG_20210417_204932_644](https://user-images.githubusercontent.com/24758741/115127585-dda07e80-9fd7-11eb-9129-f968dbb4cf41.jpg)
#176 
Is the problem known ?
Can someone help me solve this problem ?

Greeting Exodusnick

**Comment by Exodusnick** [comment]
The problem also exists on the oneplus 5t with the official sources of lineageos with microg

![IMG_20210419_141051_553](https://user-images.githubusercontent.com/24758741/115234324-31ff4780-a119-11eb-965a-480361405a49.jpg)

![IMG_20210419_141046_467](https://user-images.githubusercontent.com/24758741/115234347-375c9200-a119-11eb-8c9a-de958b6a5b39.jpg)

**Comment by Exodusnick** [comment]
Maybe this helps someone
https://android-freaks.de/attachment/1250-2021-04-start-permissioncontroller-txt/

**Comment by rawlife56** [comment]
It doesn't work on Poco F1 (beryllium) as well and shows the same loading screen. I thought it's an upstream lineage issue and wanted to wait before I report it as microg issue. Glad you reported it earlier. I didn't face this on the newer official lineage build btw. Not sure where the issue is.

**Comment by Iey4iej3** [comment]
Same for `polaris`.

**Comment by thilakm-git** [comment]
Same on OnePlus 7 Pro / guacamole

**Comment by bananer** [comment]
I can't reproduce this on any of my devices.

@Exodusnick The link you provided is no accessible without registration. Is this a logcat capture? Would you mind uploading it somewhere else?

**Comment by Exodusnick** [comment]
@bananer 

04-19 20:17:02.378 I/ActivityManager(3942): Start proc 31576:com.android.permissioncontroller/u0a167 for service {com.android.permissioncontroller/com.android.permissioncontroller.permission.service.PermissionControllerServiceImpl}
04-19 20:17:02.635 I/EdXposed(31576): Loading modules for com.android.permissioncontroller
04-19 20:17:02.942 I/CarUiInstaller(31576): CarUiInstaller started for com.android.permissioncontroller
04-19 20:17:21.571 I/ActivityTaskManager(3942): START u0 {act=android.intent.action.MANAGE_PERMISSIONS cmp=com.android.permissioncontroller/.permission.ui.ManagePermissionsActivity} from uid 1000
04-19 20:17:21.748 I/AutoRevokePermissions(31576): Parsed teamfood setting value: null
04-19 20:17:22.538 E/PermGroupLiveData(31576): Invalid permission group android.permission-group.MESSAGES
04-19 20:17:25.576 E/PermGroupLiveData(31576): Invalid permission group android.permission-group.MESSAGES
04-19 20:17:25.978 I/RenderThread(31576): type=1400 audit(0.0:277): avc: denied { search } for name="mem" dev="debugfs" ino=8729 scontext=u:r:permissioncontroller_app:s0:c167,c256,c512,c768 tcontext=u:object_r:debugfs_mali:s0 tclass=dir permissive=1 app=com.android.permissioncontroller
04-19 20:17:25.978 I/RenderThread(31576): type=1400 audit(0.0:278): avc: denied { search } for name="31576_80" dev="debugfs" ino=428294 scontext=u:r:permissioncontroller_app:s0:c167,c256,c512,c768 tcontext=u:object_r:debugfs_mali_mem:s0 tclass=dir permissive=1 app=com.android.permissioncontroller
04-19 20:17:26.068 I/RenderThread(31576): type=1400 audit(0.0:279): avc: denied { search } for name="clients" dev="debugfs" ino=2195 scontext=u:r:permissioncontroller_app:s0:c167,c256,c512,c768 tcontext=u:object_r:debugfs_ion:s0 tclass=dir permissive=1 app=com.android.permissioncontroller
04-19 20:17:26.165 I/ActivityTaskManager(3942): Displayed com.android.permissioncontroller/.permission.ui.ManagePermissionsActivity: +4s575ms
04-19 20:17:42.697 D/RecentAppStatsMixin(31525): Invalid timestamp (usage time is more than 24 hours ago), skipping com.android.networkstack.permissionconfig
04-19 20:17:42.711 D/RecentAppStatsMixin(31525): Not a user visible or instant app, skipping com.android.permissioncontroller
04-19 20:17:42.723 D/RecentAppStatsMixin(31525): Invalid timestamp (usage time is more than 24 hours ago), skipping com.mirfatif.permissionmanagerx
04-19 20:17:42.768 D/RecentAppStatsMixin(31525): Not a user visible or instant app, skipping com.android.permissioncontroller
04

**Comment by Iey4iej3** [comment]
> I can't reproduce this on any of my devices.
> 
> @Exodusnick The link you provided is no accessible without registration. Is this a logcat capture? Would you mind uploading it somewhere else?

https://github.com/lineageos4microg/docker-lineage-cicd/issues/176#issuecomment-823573952 seems to say that this was an upstream bug which is fixed, maybe we, users, should wait for the next build?

**Comment by Exodusnick** [comment]
Ok, I will build today for me times a test Rom, let's see if it is fixed.

**Comment by Exodusnick** [comment]
The problem with the authorization manager still exists , on the oneplus 5t and on the Samsung S7 with microG.
everywhere it says (is loaded...)

**Comment by Exodusnick** [comment]
> I can't reproduce this on any of my devices.
> 
> @Exodusnick The link you provided is no accessible without registration. Is this a logcat capture? Would you mind uploading it somewhere else?

I do not understand three affected users have the same problem as me and you can not confirm it ?!
We are talking about microG Rom not the normal Rom .

**Comment by Exodusnick** [comment]
@bananer I do not understand three affected users have the same problem as me and you can not confirm it ?!
We are talking about microG Rom not the normal Rom

**Comment by Iey4iej3** [comment]
> @bananer I do not understand three affected users have the same problem as me and you can not confirm it ?!
> We are talking about microG Rom not the normal Rom

They said that they were not able to reproduce the issue on any of *their* devices. It might be better for us, especially users, to be a bit more polite, to avoid punctuation like `?!`.

**Comment by Iey4iej3** [comment]
> The problem with the Permission manager still exists , on the oneplus 5t and on the Samsung S7 with microG.
> everywhere it says (is loaded...)
> 
> ![IMG_20210504_121152_353](https://user-images.githubusercontent.com/24758741/116989473-13c94800-acd2-11eb-9303-5ed95e6380fe.jpg)

Is that a clean install?

**Comment by Exodusnick** [comment]
No .

**Comment by Exodusnick** [comment]
> > @bananer I do not understand three affected users have the same problem as me and you can not confirm it ?!
> > We are talking about microG Rom not the normal Rom
> 
> They said that they were not able to reproduce the issue on any of _their_ devices. It might be better for us, especially users, to be a bit more polite, to avoid punctuation like `?!`.

Sorry My English is not so good, I use a translator.

**Comment by bananer** [comment]
We do patch the PermissionController app for signature spoofing as part of the customizations for microG. https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/signature_spoofing_patches/packages_apps_PermissionController-R.patch

Can't tell from the screenshots: On the affected devices, is there an entry for "Spoof package signature" in the list of permissions? Does it also say "Loading..."?

**Comment by Exodusnick** [comment]
@bananer Yes there is also loading...

**Comment by thilakm-git** [comment]
> We do patch the PermissionController app for signature spoofing as part of the customizations for microG. https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/signature_spoofing_patches/packages_apps_PermissionController-R.patch
> 
> Can't tell from the screenshots: On the affected devices, is there an entry for "Spoof package signature" in the list of permissions? Does it also say "Loading..."?

Yes, see here: 
![Screenshot_20210505-114650_Trebuchet](https://user-images.githubusercontent.com/59470373/117123747-b5669d00-ad97-11eb-8ac0-3a7b2e46c941.png)

**Comment by bananer** [comment]
If you're building yourself, you could try if reverting the PackageInstaller repo to one of the previous commits solves the problem.

Find the commit Id of the last commit you want to try here https://github.com/LineageOS/android_packages_apps_PackageInstaller/commits/lineage-18.1 e.g. `f4b38f2917aa5374fe49dc801b2f35b2e7be90a6`

Create a file in your `local_manifests` directory like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <extend-project name="LineageOS/android_packages_apps_PackageInstaller" revision="f4b38f2917aa5374fe49dc801b2f35b2e7be90a6" />
</manifest> 
```

Since it was working for you in previous 18.1 versions (right?), pinpointing the issue to one of the upstream commits would surely help resolving.

**Comment by Exodusnick** [comment]
No, the problem exists since I had created the first 18.1 MicroG Rom in March 2021.
And it is only noticed by a user who uses my Rom since I make all my roms available for download from 16.0 microG to 18.1 MicroG for the Samsung S7 and oneplus 5 and I think the problem is confirmed since 18.1 MicroG.

@bananer I will try the PackageInstaller repo,
And hope that it solves the problem.

**Comment by bananer** [comment]
@Exodusnick Ok, if there never was a working version of 18.1 then it's probably not an issue with recent changes in PermissionController.

You could instead help by building without the `SIGNATURE_SPOOFING` flag, to see if it is definitely our patch that causes the problem.

**Comment by Exodusnick** [comment]
i have deleted the 
-e "SIGNATURE_SPOOFING=restricted" and started the docker.sh as soon as the build process starts. i manually leased the singnature spoofing -R.pacht
via frameworks/Basic and now the permissionmanager works too.

So This one does not need  https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/signature_spoofing_patches/packages_apps_PermissionController-R.patch  .

![IMG_20210505_235117_376](https://user-images.githubusercontent.com/24758741/117214241-d3b2b400-adfc-11eb-8133-75767a00f54d.jpg)
![IMG_20210505_233109_305](https://user-images.githubusercontent.com/24758741/117214243-d4e3e100-adfc-11eb-89d8-1fd28eaf7e62.jpg)
![IMG_20210505_233103_046](https://user-images.githubusercontent.com/24758741/117214245-d4e3e100-adfc-11eb-834b-5f98c3fe3551.jpg)
![IMG_20210505_233055_283](https://user-images.githubusercontent.com/24758741/117214246-d57c7780-adfc-11eb-8396-045f9992e2c6.jpg)

**Comment by bananer** [comment]
@Exodusnick thanks for taking the time to figure this out!

If the patch for `PackageController` is the problem here, the reason I have not encountered the problem could be that I build with `SIGNATURE_SPOOFING=yes`. With unrestricted signature spoofing, a user would need the permission manager to be aware of the new permission, but with restricted spoofing, it does not really make sense.

Could somebody with an affected device do one more test and verify that a build with `SIGNATURE_SPOOFING=yes` does not have the problem?

If we can confirm that, the proper solution would be to make patching of `PackageController` conditional on `SIGNATURE_SPOOFING=yes` and no longer patch it for `restricted`. I could create a merge request for that.

**Comment by Exodusnick** [comment]
I will run a next test today with SIGNATURE_SPOOFING=yes .

**Comment by Exodusnick** [comment]
Here is my test on the Samsung S7 with
  -e "SIGNATURE_SPOOFING=yes"
![IMG_20210506_190725_823](https://user-images.githubusercontent.com/24758741/117339191-bf73c300-ae9f-11eb-9ac6-87a3d9a959ca.jpg)
![IMG_20210506_190722_055](https://user-images.githubusercontent.com/24758741/117339194-c0a4f000-ae9f-11eb-8240-65e700e9e15b.jpg)
![IMG_20210506_190714_765](https://user-images.githubusercontent.com/24758741/117339196-c0a4f000-ae9f-11eb-8837-26b7fa788555.jpg)
![IMG_20210506_191441_719](https://user-images.githubusercontent.com/24758741/117339197-c13d8680-ae9f-11eb-800c-e7b6ac6ea6e8.jpg)

**Comment by bananer** [comment]
Thank you for your initiative and  patience!

Merging is now up to @spolack

**Comment by kurt-by** [comment]
Thank you @bananer for new builds with updated security patch level. Tested bacon. The Permission screen still shows "Loading..." on permission manager screen of June 17 build. Even for "Spoof package signature". Addionally all permissions in microG self-check have been missing after update from May build. I enabled all but "location in the background" and "receive text messages (SMS)" by tapping.

After factory reset the microG self-check has all checked, but permission manager still says "Loading..."

**Comment by rawlife56** [comment]
I agree @kurt-by 
Although not facing the microg permission issue you mentioned but still the permission manager is stuck in loading on beryllium. 
Thanks for your work btw @bananer

**Comment by Iey4iej3** [comment]
Did you see the post https://github.com/lineageos4microg/docker-lineage-cicd/issues/166#issuecomment-863343071 which says that this patch is **not** merged into this build so we need to check this in the next builds?

**Comment by rawlife56** [comment]
Just saw that. Thanks @ley4jej3 for pointing it out.
