### ISSUE TITLE
Sailfish: LineageOS 16 build has (significantly) different size than what is available on download.lineage.microg.org

### ISSUE THREAD

**Issue by hkzlab** [lineageos4microg/docker-lineage-cicd#45]
Hello,
I'm trying to build myself a custom image for my Sailfish Pixel: the image i was able to build installs, boots and works fine, but is significantly smaller than the one offered for sailfish at  download.lineage.microg.org (or even the official LineageOS image, for the matter).
An example of such difference:

- lineage-16.0-20190717-microG-sailfish.zip 578 MB
- lineage-16.0-20190719-nightly-sailfish-signed.zip 576 MB
- **lineage-16.0-20190719-UNOFFICIAL-sailfish.zip** 533 MB

I suspect the difference is due to missing radio/bootloader in my image (i can't find any reference to them if i run `strings` on the payload.bin file), which means that in the long run I'll have to update them manually via fastboot instead of relying on the LineageOS updater i setup for my builds.

Here is the command I use to start the build:

```bash
docker run \
    --rm \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=sailfish" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "LOCAL_MIRROR=false" \
    -e "INCLUDE_PROPRIETARY=false" \
    -e "CCACHE_SIZE=200G" \
    -e "OTA_URL=https://redacted/LineageOTA/api" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/lineage:/srv/src" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/zips:/srv/zips" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/logs:/srv/logs" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/cache:/srv/ccache" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/keys:/srv/keys" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/custom_builds/manifests/los16-sailfish:/srv/local_manifests" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/ext-cert:/srv/ext-cert" \
    lineageos4microg/docker-lineage-cicd
```
Here is the manifest i have in `local_manifests`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
        <project name="LineageOS/android_device_google_sailfish" path="device/google/sailfish" remote="github"  revision="lineage-16.0" />
        <project name="LineageOS/android_device_google_marlin" path="device/google/marlin" remote="github"  revision="lineage-16.0" />
        <project name="LineageOS/android_kernel_google_marlin" path="kernel/google/marlin" remote="github"  revision="lineage-16.0" />
        <project name="TheMuppets/proprietary_vendor_google" path="vendor/google" remote="github"  revision="lineage-16.0" />
        <project name="LineageOS/android_packages_resources_devicesettings" path="packages/resources/devicesettings" remote="github" revision="lineage-16.0" />
</manifest>
```

The size difference is not tied to missing microg packages (I also tried to include them, but they just changed around ~2MB in the build), so it must be because of something I'm missing/doing wrong in the build, but the official documentation of `docker-lineage-cicd` doesn't mention anything particular about sailfish. 
Any ideas? The builds on download.lineage.microg.org have the correct size, so someone must know.

**Comment by corna** [comment]
Why are you manually specifying the manifests? The device is officially supported, try to set `INCLUDE_PROPRIETARY` to `true` without specifying any additional manifest.

Note that `SIGNATURE_SPOOFING=restricted` means that only priv-apps can obtain the signature spoofing permission (so, apps that were either bundled at compile-time or later added through a zip in TWRP); if you want microG, should bundle add them as `CUSTOM_PACKAGES`.

**Comment by hkzlab** [comment]
@corna I tried without a custom manifest and setting INCLUDE_PROPRIETARY to true. No changes, i get the exact same result. It does not solve the issue, nor make it better in any way.

As for `SIGNATURE_SPOOFING=restricted`, I set it because i then use magisk to overlay the microg apps with NanoDroid onto /system. No need to include them on the image.

**Comment by hkzlab** [comment]
@corna I took the time to redo a build, just to be super-sure that i did not leave anything in my manifest or command line to build the image.

Here is my command line now:
```sh
docker run \
    --rm \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=sailfish" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "LOCAL_MIRROR=false" \
    -e "INCLUDE_PROPRIETARY=true" \
    -e "BUILD_OVERLAY=false" \
    -e "CCACHE_SIZE=200G" \
    -e "OTA_URL=https://losota.hkzlab.info/LineageOTA/api" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/lineage:/srv/src" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/zips:/srv/zips" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/logs:/srv/logs" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/cache:/srv/ccache" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/keys:/srv/keys" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/ext-cert:/srv/ext-cert" \
    -v "/mnt/storage/users/fbattaglia/los-build/los/overlay-tmp:/srv/tmp" \
    lineageos4microg/docker-lineage-cicd
```

And here is the result i obtained from the build:
lineage-16.0-20190821-UNOFFICIAL-sailfish.zip 531M
While, the latest microg rom built on 2019-08-22 is 575.1 MB
Quite a difference...

**Comment by corna** [comment]
Try to compare the content of our and your image (unzip, extract the partition with [this](https://github.com/cyxx/extract_android_ota_payload) and see which partition is smaller, then mount them and run `diff -rq yours/ ours/`)

**Comment by hkzlab** [comment]
Done, no need to run the diff...
Here is the content of an image from LineageOS extracted from the payload.bin
```
aboot.img
bootlocker.img
devcfg.img
keymaster.img
rpm.img
vendor.img
apdp.img
cmnlib32.img
hosd.img
modem.img
system.img
xbl.img
boot.img
cmnlib64.img
hyp.img
pmic.img
tz.img
```

The image created with docker-lineage-cicd contains only system, vendor and boot instead, all the others are missing.

**Comment by spolack** [comment]
Sailfish was promoted to LineageOS 17.1 in the meanwhile and therefore this isssue is unlikely to still occur. If it does please reopen.
